# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('session', models.CharField(db_index=True, default='', max_length=256)),
                ('wx_openid', models.CharField(db_index=True, max_length=256)),
                ('wx_unionid', models.CharField(db_index=True, default='', max_length=256)),
                ('wx_session_key', models.CharField(db_index=True, default='', max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'common_user',
            },
        ),
    ]
