# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_sn', models.CharField(max_length=32, unique=True)),
                ('user_id', models.IntegerField()),
                ('total_amount', models.IntegerField(default=0)),
                ('postage', models.IntegerField(default=0)),
                ('amount_payable', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oms_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=64)),
                ('market_price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='order_sn', on_delete=django.db.models.deletion.CASCADE, to='common.Order', to_field='order_sn')),
            ],
            options={
                'db_table': 'oms_order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('province', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('district', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('mobile', models.CharField(blank=True, max_length=16)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(db_column='order_sn', on_delete=django.db.models.deletion.CASCADE, to='common.Order', to_field='order_sn')),
            ],
            options={
                'db_table': 'oms_order_receiver',
            },
        ),
    ]
