# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBannerImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(default='', max_length=1024)),
                ('refer', models.CharField(default='', max_length=1024)),
                ('sort', models.IntegerField(db_index=True)),
                ('status', models.IntegerField(db_index=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'home_banner_image',
            },
        ),
    ]
