# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='entry',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
