# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_usermodel_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PintuanOrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_id', models.IntegerField()),
                ('price', models.IntegerField(db_index=True)),
                ('start_order_id', models.IntegerField()),
                ('pintuan_order_status', models.IntegerField(db_index=True, default=0)),
                ('finish_time', models.DateTimeField(db_index=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pintuan',
            },
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='pintuan_id',
            field=models.IntegerField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='order_sn',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='orderlogisticsmodel',
            name='order_sn',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_status',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ordertrademodel',
            name='order_sn',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='ordertrademodel',
            name='trade_no',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='ordertrademodel',
            name='trade_status',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
