# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_homebannerimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsSkuModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField(db_index=True)),
                ('image_url', models.CharField(default='', max_length=1024)),
                ('property_vector', models.CharField(default='', max_length=512)),
                ('price', models.IntegerField(db_index=True)),
                ('stock', models.IntegerField(db_index=True)),
                ('status', models.IntegerField(db_index=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'goods_sku',
            },
        ),
    ]
