# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180217_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsmodel',
            old_name='taobao_id',
            new_name='supply_item_id',
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='supply_source',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='pintuanmodel',
            name='success_target',
            field=models.IntegerField(default=0),
        ),
    ]
