# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180212_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='entry',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_sn',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pintuan_id',
            field=models.IntegerField(db_index=True, default=-1),
        ),
    ]
