# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_goodsskumodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLogistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_sn', models.CharField(max_length=32)),
                ('com', models.CharField(max_length=32)),
                ('nu', models.CharField(max_length=32)),
                ('data', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_logistics',
            },
        ),
    ]
